### register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "nickname":"usertest03",
  "email":"dtekchannel02@gmail.com",
  "phone_number":"0829932992",
  "password":"user123"
}

### OTP
POST http://localhost:3000/api/v1/auth/verifyOTP
Content-Type: application/json

{
  "email":"dtekchannel02@gmail.com",
  "otp": "HeicvG"
}


### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email":"dtekchannel02@gmail.com",
  "password":"user12345"
}

### forgot password
POST http://localhost:3000/api/v1/auth/forgotPassword
Content-Type: application/json

{
    "email": "dtekchannel02@gmail.com"
}

### reset password
POST http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InVzZXJ0ZXN0MDMiLCJlbWFpbCI6ImR0ZWtjaGFubmVsMDJAZ21haWwuY29tIiwiaWF0IjoxNzAxMDk0NDI5LCJleHAiOjE3MDEwOTgwMjl9.-lqAyLC5zzJo__XuvrlIl2zoQidD9gq_F52zz_JKrkc
Content-Type: application/json

{
  "password":"user12345",
  "confirm_password":"user12345"
}

### Whoami
GET http://localhost:3000/api/v1/auth/whoami
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWRBZG1pbiI6ImFkbWluLWNvdXJzZS1odWIiLCJpYXQiOjE3MDEyMzI4MzAsImV4cCI6MTcwMTMxOTIzMH0.IC-DZjXAhQm-RoRVzkHlb8K3sm4TS3TsasQL65HtPK0

### Login admin
POST http://localhost:3000/api/v1/auth/admin/login
Content-Type: application/json

{
  "idAdmin":"admin-course-hubb@gmail.com",
  "password":"admin123"
}

###
POST http://localhost:3000/api/v1/courses
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWRBZG1pbiI6ImFkbWluLWNvdXJzZS1odWJiQGdtYWlsLmNvbSIsImlhdCI6MTcwMTI2NTgwMiwiZXhwIjoxNzAxMzUyMjAyfQ.mfqgNMidKI3o83qNDCXLSoj1GUd450vliVCfmapeQVo

{
  "title": "NEXTJS lvl 1",
  "description": "Belajar NEXTJS paling gampang",
  "image": " ",
  "price": 999999,
  "author": "CourseHub",
  "level": "beginner",
  "category_id": 2,
  "requirements":  [
          "React Dasar",
          "Express"
        ],
  "chapters": [
    {
      "name": "Chapter selanjutnya",
      "modules": [
        {
          "title": "Module 1",
          "duration": 60,
          "url": "https://youtu.be/kWT1uGvhWp8?feature=shared"
        },
        {
          "title": "Module 2",
          "duration": 45,
          "url": "https://youtu.be/kWT1uGvhWp8?feature=shared"
        }
      ]
    }
  ]
}

###
GET http://localhost:3000/api/v1/courses?levels=beginner
Content-Type: application/json

###
GET http://localhost:3000/api/v1/courses
Content-Type: application/json

###
GET http://localhost:3000/api/v1/courses?levels=beginner&page=2&pageSize=10
Content-Type: application/json

### get all course
GET http://localhost:3000/api/v1/courses
Content-Type: application/json

### get course with pagination
GET http://localhost:3000/api/v1/courses?page1&limit=10
Content-Type: application/json


### get detail courses
GET http://localhost:3000/api/v1/courses/1
=======

###
GET http://localhost:3000/api/v1/courses
Content-Type: application/json


###
PUT http://localhost:3000/api/v1/courses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWRBZG1pbiI6ImFkbWluLWNvdXJzZS1odWIiLCJpYXQiOjE3MDE0MzAyNzUsImV4cCI6MTcwMTUxNjY3NX0.1MT9lM1xupj_H8ZL5JIAq-JLjJwuF9w4GIfamNPXag0

{
  "title": "NEXTJS lvl 1 ",
  "description": "updated",
  "price": 100,
  "image": "https://google.com",
  "requirements": [
        "React Dasar",
        "Express"
      ],
  "author": "coursehubh",
  "level": "intermediate",
  "chapters": [
    {
      "name": "Chapter 1",
      "modules": [
        {
          "title": "Module 1",
          "duration": 10,
          "url": "https://google.com"
        },
        {
          "title": "Module 2",
          "duration": 15,
          "url": "https://google.com"
        }
      ]
    },
    {
      "name": "Chapter 2",
      "modules": [
        {
          "title": "Module 3",
          "duration": 20,
          "url": "https://google.com"
        }
      ]
    }
  ]
}
